### PR TITLE
Korean translation

### PR DESCRIPTION
**Pull request by Johnmacrocraft**
Well, why not :)

### CODE REVIEW

**Comment by Johnmacrocraft** [comment]
I just realised that you guys have merged two other PRs just now. But I currently have some changes that I haven't pushed yet, so please be patient.

**Comment by bilde2910** [comment]
Thank you so much for this contribution! I'll make sure this gets merged and included in the plugins.

**Comment by bilde2910** [comment]
Thanks @Johnmacrocraft, merged the changes in #169 now 👍

**Comment by bilde2910** [comment]
Are there any other changes that you want to include before I submit to the web stores?

**Comment by Johnmacrocraft** [comment]
Ah no, the translation is now okay; you can submit it to the web stores now!

**Comment by Johnmacrocraft** [comment]
Add: I just realised that there's another part that should be fixed (I hate my life oof)... But it's not a big problem that should be fixed immediately right now. Since it's just a nit and does not affect the contents, it doesn't really matter. You can change the following later when you're willing to!

Current: bilde2910**를** 찾으실 수 있습니다
New: bilde2910**을** 찾으실 수 있습니다

**Comment by bilde2910** [comment]
Sure thing; looks like you noticed the migration to Crowdin pretty quickly as well. I'll make sure that the changes are pulled, and update the store descriptions. Thanks again!

**Pull request merged**
