### PR TITLE
GH-468 GH-453 GH-451 GH-450 GH-402 GH-349 GH-336 GH-299 add new sites

### PR DESCRIPTION
**Pull request by dada513**
closes: https://github.com/StopModReposts/Illegal-Mod-Sites/issues/468 closes: https://github.com/StopModReposts/Illegal-Mod-Sites/issues/453 closes: https://github.com/StopModReposts/Illegal-Mod-Sites/issues/451 closes: https://github.com/StopModReposts/Illegal-Mod-Sites/issues/450 closes: https://github.com/StopModReposts/Illegal-Mod-Sites/issues/402 closes: https://github.com/StopModReposts/Illegal-Mod-Sites/issues/349 closes: https://github.com/StopModReposts/Illegal-Mod-Sites/issues/336 closes: https://github.com/StopModReposts/Illegal-Mod-Sites/issues/229

### CODE REVIEW

**Review by berrysauce — CHANGES_REQUESTED** [review]
Remove "mcbedrock.com" (duplicate)

**Comment by Brandonbr1** [comment]
> _No description provided._

also add https://github.com/StopModReposts/Illegal-Mod-Sites/issues/471

**Review by Brandonbr1 — CHANGES_REQUESTED** [review]
@dada513 as berrysauce said remove the website **mcbedrock.com** it is a duplicate please remove it😄

**Comment by dada513** [comment]
> @dada513 as berrysauce said remove the website **mcbedrock.com** it is a duplicate please remove itsmile

I will, I didnt have time recently to look at PRs here

**Comment by dada513** [comment]
sorry for the wait, was a bit busy. Now I have more time, I will also review other issues and @Brandonbr1's PR

**Review by Brandonbr1 — CHANGES_REQUESTED** [review]
please add this to the description😄

closes: #468 closes: #453 closes: #451 closes: #450 closes: #402 closes: #349 closes: #336 closes: #229

**Comment by dada513** [comment]
> please add this to the descriptionsmile
> 
> closes: #468 closes: #453 closes: #451 closes: #450 closes: #402 closes: #349 closes: #336 closes: #229

the commit name has issue references, when this is merged it works the same way.

**Review by berrysauce — APPROVED** [review]

**Pull request merged**
