### PR TITLE
Create LICENSE.txt

### PR DESCRIPTION
**Pull request by Brandonbr1**

### CODE REVIEW

**Review by dada513 — CHANGES_REQUESTED** [review]
LICENSE.MD -> LICENSE.md (lowercase md)

Other than that, LGTM

**Comment by Brandonbr1** [comment]
@dada513 ok i changed the file extension to a lower case .md as you asked me to 😊😀

**Review by dada513 — CHANGES_REQUESTED** [review]
sorry for not noticing it before, but seems since this is plaintext, the extension should be changed to `.txt`. Markdown has its own way of handling newlines, and currently it looks like [this](https://github.com/Brandonbr1/Illegal-Mod-Sites/blob/patch-11/LICENSE.md)

Though I have not been able to find the entire license text in markdown, officially. So might be better to use a .txt

**Review by dada513 — APPROVED** [review]

**Comment by Brandonbr1** [comment]
> Though I have not been able to find the entire license text in markdown, officially. So might

yea your right it looks better in .txt plus i found a repository with better formatting

from [here](https://github.com/santisoler/cc-licenses)  by santisoler

**Comment by dada513** [comment]
yeah looks good to me

**Comment by berrysauce** [comment]
Putting this on hold for now since I have to review our licensing terms again.

**Comment by dada513** [comment]
@berrysauce btw the license is mentioned in https://github.com/StopModReposts/Illegal-Mod-Sites/wiki/API-access-and-formats

**Comment by Brandonbr1** [comment]
> Putting this on hold for now since I have to review our licensing terms again.

@berrysauce 
Creative Commons Attribution-ShareAlike 4.0 International is mentioned [https://github.com/StopModReposts/Illegal-Mod-Sites/wiki/API-access-and-formats](in:https://github.com/StopModReposts/Illegal-Mod-Sites/wiki/API-access-and-formats)

**Comment by dada513** [comment]
yeah licenses are werid rn. At least extension has the best license ever made 😆

**Comment by berrysauce** [comment]
That's why I need time to review this. Sorry, but I can't just merge a legal document that quickly

**Comment by Brandonbr1** [comment]
> legal document



> Exactly, that's why I need time to review this. Sorry, but I can't just merge a legal document that quickly

ok take as much time as you need

but here is something might help you decide:
[https://tldrlegal.com/license/creative-commons-attribution-sharealike-4.0-international-(cc-by-sa-4.0)](https://tldrlegal.com/license/creative-commons-attribution-sharealike-4.0-international-(cc-by-sa-4.0))

**Comment by Brandonbr1** [comment]
@dada513 @berrysauce 
how does this custom License i made sound?
tell me if i should make any changes to t

StopModRepost License

Copyright (c) 2022 StopModReposts Team

- you may  modify any of the Licensed material

- you may not use this for any Commercial use's
the Licensed material and derivatives may not be used for any Commercial purposes 

- you may not use this in Private use
the Licensed material may  be used and modified in private

- you must include the above copyright notice 

- state the changes
changes made to the Licensed material must be documented


- you must keep the mod with the same License


The StopModReposts Team  consists of:
- berrysauce
-  falseresync
- dada513

Liability:
THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.

**Comment by dada513** [comment]
@Brandonbr1 I think it would be better to use a license that has been tested in court and only a custom one if its the only way out.

**Comment by berrysauce** [comment]
Closed with #516

**Pull request closed without merging**
